services:
  - type: web
    name: inovar-backend
    env: docker
    plan: free
    region: oregon
    buildCommand: docker build -t inovar-backend .
    startCommand: ./main
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Inovar2026!Secure@db.bxbupbnjcingfvjszrau.supabase.co:5432/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        value: https://bxbupbnjcingfvjszrau.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4YnVwYm5qY2luZ2Z2anN6cmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzODEyMjEsImV4cCI6MjA4NTk1NzIyMX0.OzBxS46bmR5OyxmS-DKFW7RRfEfVcgbhEKDWJSpMLOA
